apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirp-client
  namespace: enoch-final
  labels:
    app: chirp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirp-client
  template:
    metadata:
      labels:
        app: chirp-client
    spec:
      containers:
        - name: chirp-client
          image: ${{ secrets.DOCKER_USERNAME }}/chirpclient:${IMAGE_TAG}
          ports:
            - containerPort: 80
          env:
            - name: VITE_URL
              value: https://enoch-chirp.duckdns.org/api
