apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enoch-chirp-ingress
  namespace: enoch-final
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - enoch-chirp.duckdns.org # Frontend Client
        - api.enoch-chirp.duckdns.org # Backend Server
  rules:
    - host: enoch-chirp.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirp-client-service
                port:
                  number: 80
    - host: api.enoch-chirp.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirp-server
                port:
                  number: 8080
